### ISSUE TITLE
Running image with traefik reverse proxy

### ISSUE THREAD

**Issue by Rashidsalim** [krish512/ReviveDockerImage#3]
Hi,
Here is my docker-compose file which I'm currently using to run your image.
```
version: '3'
networks:
  proxy:
    external: true
services:
  revive:
    build:
      context: revive/
    restart: always
    volumes:
      - revive_vm:/var/www/html
    labels:
      - traefik.backend=revive
      - traefik.frontend.rule=Host:ads.example.com
      - traefik.docker.network=proxy
      - traefik.enable=true
      - traefik.port=80
    networks:
      - proxy
volumes:
  revive_vm:
    driver: local
```

The image runs but after installation I get this error
![screenshot_7](https://user-images.githubusercontent.com/37694861/50057010-cc2fd900-0175-11e9-8ff4-4289d60dedcb.jpg)
And after pressing continue, the adserver seems broken.
![screenshot_8](https://user-images.githubusercontent.com/37694861/50057018-e073d600-0175-11e9-9f5a-51fb475fcafc.jpg)
I do not see any logs in the directory that can help me debug the issue. This only occurs when I'm installing with traefik but if I run the image with `docker run` and no subdomain, it works perfectly. Would really appreciate some assistance. I suspect it could be a permissions issue with the plugin directory which I have give write access but it doesn't seem to solve it.
